version: '3.8'

services:
  # ----------------------------
  # Backend microservices BASE/PROD
  # ----------------------------
  user_service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
      target: runtime  # usa apenas stage de runtime
    image: userservice-prod
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      - db
      - redis
      - rabbitmq

  room_service:
    build:
      context: ./RoomService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookingDb;User Id=sa;Password=tubarao16H!4121
    depends_on:
      - db
      - redis

  reservation_service:
    build:
      context: ./ReservationService
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookingDb;User Id=sa;Password=tubarao16H!4121
    depends_on:
      - db
      - redis
      - rabbitmq

  notification_service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookingDb;User Id=sa;Password=tubarao16H!4121
    depends_on:
      - db
      - rabbitmq

  # ----------------------------
  # Database
  # ----------------------------
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=tubarao16H!4121
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

  # ----------------------------
  # RabbitMQ for messaging
  # ----------------------------    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # porta do broker
      - "15672:15672" # porta do dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # ----------------------------
  # Redis cache
  # ----------------------------
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
  